(define (problem pb5_p03)
  (:domain blocksworld)
  (:objects a b c d e - block)
  (:init (onTable a) (onTable b) (onTable c) (onTable d) (onTable e)
    (clear a) (clear b) (clear c) (clear d) (clear e))
  (:goal (and (on d e) (onTable e) (on a b) (on b c) (onTable c) (clear d) (clear a)))
)